FROM node:20

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

EXPOSE 8080

CMD  ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && npx prisma db seed && node dist/src/main.js"]